dist: trusty
sudo: required

language: python
python:
  - "2.7"

# command to install dependencies
install: 
    #cd imhere 
    pip install -t lib -r requirements.txt

# command to run tests
script: python fake_pytest
