dist: trusty
sudo: required
language: python
python:
- '2.7'
install: pip install -t lib -r requirements.txt
script: python fake_pytest.py
before_install:
- openssl aes-256-cbc -K $encrypted_d4d6810438b5_key -iv $encrypted_d4d6810438b5_iv
  -in 6156-baa6a7adb5ec.json.enc -out ~\/Downloads/6156-baa6a7adb5ec.json -d
